### ISSUE TITLE
Could you push the 0.1.4 version?

### ISSUE THREAD

**Issue by bhbbbbb** [seangohck/Ariake-Pale#1]
Hi seangohck,

I just found this wonderful theme and would like to contribute for more enhancement for python.

However, it seems that you didn't push the 0.1.4 version. It would be much easier for me if I can start with 0.1.4!

thanks a lot for you work!

**Comment by seangohck** [comment]
Hey @bhbbbbb , I have pushed the latest `0.1.4` version. To be honest, I am not sure whether it changes anything or causes any problem, but you can just make changes from there.

**Comment by bhbbbbb** [comment]
thanks a lot!
